favicon:
  href: /favicon.ico # Favicon of your site.
  type: image/x-icon # Icon type, possible values are(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

search: https://cn.bing.com/search?q= # https://www.google.com/search?q==
order_by: date # date,-date,title,url,...
head: '<!--<script src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7114121088728794" crossorigin="anonymous" async></script>-->' # Add anything to <head></head>


archives:
  switch: false # true,false Switching this function.
  categories: [算法,游戏] # Only the categories you set will be displayed on the archive page.

menu:
  归档: /archives
  关于: /about

footer_link:
  涯木笔谈: https://www.nickyam.com/
  还有书籍: https://github.com/Yet-The-Books/hexo-theme-yet-the-books

github:
  repo: nickyam/book.github.io # nexmoe/books
  edit: true # true,false
  history: true # true,false

analytics: # 统计系统，目前支持 Google analytics.js 统计、Google Tag Manager 统计、CNZZ 统计、腾讯统计、51.La统计、百度统计
  google_site_id: #<ID>
  gtags_site_id: #<ID>
  cnzz_site_id: #<ID>
  tencent_site_id: #<ID>
  la_site_id: #<ID>
  baidu_site_id: 0eb554421764eafae9cffc2f4dc736b5 #<ID>
  gtm_container_id: #<ID>

cdn: # 这里可以修改站点使用的库的CDN
  disqusjs: 
    css: https://cdn.jsdelivr.net/npm/disqusjs@1.2.5/dist/disqusjs.min.css
    js: https://cdn.jsdelivr.net/npm/disqusjs@1.2.5/dist/disqus.min.js
  gitalk:
    css: https://cdn.jsdelivr.net/npm/gitalk@1.5.0/dist/gitalk.min.css
    js: https://cdn.jsdelivr.net/npm/gitalk@1.5.0/dist/gitalk.min.js
  valine:
    js: https://cdn.jsdelivr.net/npm/valine

 